<html>
<head>
    <title>Connect Me</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>
<body>
<h1>New connection</h1>

<form class="pure-form" method="post" action="/savedetails">
    <label for="username">Your Name</label>
    <input name="username" id="username" type="text" size="20" /><br />

    <label for="age">age</label>
    <input name="age" id="age" type="integer"/><br />

    <label for="location">Location</label>
    <select name="location" id="location" type="text" size="20"></select><br />

    <input type="submit" class="pure-button" value="Create" />
</form>

</body>
</html>


