<html>
<head>
    <title>Slim 3 App</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>
<body>
<h1>USERS</h1>

<?php
if($data['users'] && is_array($data['users'])):
?>
<table class="pure-table">
    <tr>
        <th>Username</th>
        <th>Id</th>
        <th>Age</th>
        <th>Location</th>
    </tr>

<?php
    $odd = 1;
    foreach($data['users'] as $user): ?>

        <tr <?=$odd ? "class=\"pure-table-odd\"" : ""; ?>>
        <td>
        <a href="<?=$router->pathFor('user-detail', ['id' => $user->getId()])?>">
        <?=$user->getUsername() ?>
        </a>
        </td>
        <td><?=$user->getId() ?> </td>
        <td><?=$user->getAge() ?> </td>
        <td><?=$user->getLocation() ?> </td></tr>

    <?php 
        $odd = $odd ? 0 : 1;
    endforeach; ?>
</table>
<?php else: ?>
<p>No current users</p>

<?php endif; ?>


</body>
</html>