<html>
<head>
    <title>Slim 3 App</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>
<body>
<h1>USER</h1>

<?php
if($data['user']):
?>
<table class="pure-table">
    <tr>
        <th>Username</th>
        <th>Age</th>
        <th>Location</th>
    </tr>
        <tr>
        <td>
        <?php 
        $user=$data['user'];
        ?>
        <?=$user->getUsername()?>
        </td>
        <td>
        <?=$user->getAge()?>
        </td>
        <td>
        <?=$user->getLocation()?>    
        </td>
       </tr>
</table>

<?php else: ?>
<p>No current users</p>

<?php endif; ?>

<a href="<?=$router->pathFor('take_user_details')?>"><button type="submit"> wanna connect ??</button></a> 


</body>
</html>